# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kat Fukui
email: katherinefukui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Kat Fukui. Product Designer building inclusive communities.
site_image: /images/site-image.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.katfukui.com" # the base hostname & protocol for your site
twitter_username: katfukui
github_username:  katmeister
dribbble_username: katfukui
repo: https://github.com/katmeister

# http://jekyllrb.com/docs/permalinks/
permalink:   /:title/

# Build settings
markdown: kramdown
